format = """
[ ](contrast3)\
$username\
[](bg:contrast2 fg:contrast3)\
$directory\
[](fg:contrast2 bg:contrast1)\
$git_branch\
$git_status\
[](fg:contrast1 bg:contrast0)\
$lua\
$python\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[ ](fg:contrast0)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:contrast3"
style_root = "bg:contrast3"
format = '[$user ]($style)'

[directory]
style = "bg:contrast2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"python" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:contrast1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:contrast1"
format = '[($all_status$ahead_behind )]($style)'

[golang]
symbol = " "
style = "bg:contrast0"
format = '[[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "bg:contrast0"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:contrast0"
format = '[ $symbol ($version) ( $virtualenv )]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
